WebApplication/Areas/Admin/Controllers/NewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WebApplication.Core.Domains;
using WebApplication.Infrastructure.Repository;

namespace WebApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class NewsController : Controller
    {
        private readonly INewsRepository _newsRepository;

        public NewsController(INewsRepository newsRepository) => _newsRepository = newsRepository;

        private readonly WebApplicationDbContext _context = new WebApplicationDbContext();

        public IActionResult Index()
        {
            
            //var item = await _newsRepository.FindAll();

            return View(_context.News);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(News model)
        {
            if (ModelState.IsValid)
            {
                News item = new News
                {                                      
                     Body = Request.Form["editor1"].ToString(),
                     addedBy = $"admin",
                     publishedDate = DateTime.Now

                };

                //_newsRepository.Save(item);

                _context.News.AddRange(item);
            }
            else
            {
                return View(model);
            };

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var queryresult = await _newsRepository.Get(id);
           // var queryresult = await _context.News.Find(id);


            if (queryresult == null)
            {
                return NotFound();
            }

            return View(queryresult);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var queryresult = await _newsRepository.Get(id);
            if (queryresult == null)
            {
                return NotFound();
            }

            return View(queryresult);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(News model)
        {

            if (ModelState.IsValid)
            {
                News item = new News
                {
                      Title = model.Title,
                      Body = Request.Form["editor1"].ToString(),

                };


                await _newsRepository.Update(item);

                return RedirectToAction("Index");
            }
            return View();
        }


        public async Task<IActionResult> Delete(string id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var queryresult = await _newsRepository.Get(id);

            if (queryresult == null)
            {
                return NotFound();
            }

            return View(queryresult);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var item = await _newsRepository.Get(id);
            await _newsRepository.Delete(item);

            return RedirectToAction("Index");
        }
   
    }
}

WebApplication/Areas/Admin/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Identity;
using WebApplication.Infrastructure;
using WebApplication.Infrastructure.Extensions;
using WebApplication.Infrastructure.ViewModels;

namespace WebApplication.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]

    public class RolesController : BaseController
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger _logger;
     
        public RolesController(
           UserManager<IdentityUser> userManager,         
           RoleManager<IdentityRole> roleManager,
           ILoggerFactory loggerFactory,
           ApplicationDbContext context,
           UserStore<IdentityUser, IdentityRole> users) :
           base(userManager, context,users)
        {
            _roleManager = roleManager;
            _logger = loggerFactory.CreateLogger<RolesController>();
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles;

            return View(roles.ToList().ToListViewModel());
        }

        public IActionResult Create()
        {
            return View();
        }
 
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {

            if (ModelState.IsValid)
            {
                var role = model.ToEntity();

                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            
            return View(model);
        }

        [ActionName("Delete")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            
            var role = await _roleManager.FindByIdAsync(id);

            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string id)
        {
        
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                return NotFound();
            }

                return View(role.ToViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
           
            var role = await _roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                role = model.UpdateEntity(role);

                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            
            return View(model);
        }

    }
}

WebApplication/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Data;
using Microsoft.AspNetCore.Authorization;
using MongoDB.Bson.Serialization.Attributes;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using WebApplication.Identity;
using WebApplication.Infrastructure;
using WebApplication.Infrastructure.ViewModels;
using WebApplication.Infrastructure.Extensions;
using WebApplication.Core.Domains;

namespace WebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
     public class UsersController : BaseController
    {
        private readonly ILogger _logger;
        private readonly RoleManager<IdentityRole> _roleManager;
        protected readonly RoleStore<IdentityUser, IdentityRole> _roleStore;
        public UsersController(
            UserManager<IdentityUser> userManager,
            ILoggerFactory loggerFactory,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context,
            UserStore<IdentityUser,IdentityRole> userStore
          
            ) : base(userManager,context, userStore)
        {
            _roleManager = roleManager;
            _logger = loggerFactory.CreateLogger<UsersController>();

   
        }


        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? page
            )
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            
          
            var u = _userManager.Users.ToList().ToListUserAdminViewModel();

            var users = from m in u
                         select m;

                        
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.UserName.Contains(searchString)
                                       || s.Email.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    users = users.OrderByDescending(s => s.UserName);
                    break;
                case "Date":
                    users = users.OrderBy(s => s.CreatedOn);
                    break;
                case "date_desc":
                    users = users.OrderByDescending(s => s.CreatedOn);
                    break;
                default:
                    users = users.OrderBy(s => s.UserName);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<UserAdminViewModel>.CreateAsync(users.ToList(), page ?? 1, pageSize));

        }


        public async Task<IActionResult> Details(string id)
        {
     
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);          
        }
        
        public async Task<IActionResult> Edit(string id)
        {
           
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            ViewBag.Roles = _roleManager.Roles.ToList().ToListViewModel();

            return View(user.ToViewModel());
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel model)
        {

            if (ModelState.IsValid)
            {                 
                var user = await _userManager.FindByIdAsync(model.Id);

                if (user == null)
                {
                    return NotFound();
                }

                var role = _userManager.GetRolesAsync(user).Result;

                await _userManager.RemoveFromRolesAsync(user, role);

                await _userManager.AddToRolesAsync(user,model.RoleNames);
                
                await _userManager.SetEmailAsync(user, model.Email);
                await _userManager.SetUserNameAsync(user, model.UserName);

                
                //user = model.UpdateEntity(user);

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            ViewBag.Roles = _roleManager.Roles.ToList().ToListViewModel();

            return View(model);
        }

        public async Task<IActionResult> ChangePassword(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(UserChangePasswordViewModel model)
        {

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);

                if (user == null)
                {
                    return NotFound();
                }

                await _userManager.RemovePasswordAsync(user);
                await _userManager.AddPasswordAsync(user, model.Password);

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            return View(model);
        }

        [ActionName("Delete")]
        public async Task<IActionResult> Delete(string id)
        {
          
            if (id == null)
            {
                return NotFound();
            }

            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }


        public IActionResult Create()
        {
           
            ViewBag.Roles = _roleManager.Roles.ToList().ToListViewModel();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserViewModel model)
        {

           if (ModelState.IsValid)
           {
               var user = model.ToEntity();

               var result = await _userManager.CreateAsync(user, model.Password);

               var roles = await _userManager.AddToRolesAsync(user, model.RoleNames);

               if (result.Succeeded)
               {
                   return RedirectToAction("Index");
               }
               else
               {
                   AddErrors(result);
               }
           }

           ViewBag.Roles = _roleManager.Roles.ToList().ToListViewModel();

           return View(model);
        }
            
  
        }

    }

    
  

WebApplication/Areas/Admin/Views/Shared/_Footer.cshtml
<footer class="main-footer">

</footer>

WebApplication/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>

    <environment names="Development">
        <link href="~/backend/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/backend/css/bootstrap-reset.css" rel="stylesheet">
        <link href="~/backend/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/backend/css/slidebars.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
        <link href="~/backend/css/style.css" rel="stylesheet">
        <link href="~/backend/css/style-responsive.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="~/backend/css/mixins.css">
        <link rel="stylesheet" type="text/css" href="~/backend/css/global.css">
        <link rel="stylesheet" type="text/css" href="~/backend/css/mystyle.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" asp-append-version="true" />
        <link href="~/backend/css/slidebars.css" rel="stylesheet" asp-append-version="true">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
        <link href="~/backend/css/style.css" rel="stylesheet">
        <link href="~/backend/css/style-responsive.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="~/backend/css/mixins.css">
        <link rel="stylesheet" type="text/css" href="~/backend/css/global.css">
        <link rel="stylesheet" type="text/css" href="~/backend/css/mystyle.css">
    </environment>
</head>
<body>

    <!--header start-->
    <header class="header white-bg">
        <div class="sidebar-toggle-box">
            <i class="fa fa-bars"></i>
        </div>
        <!--logo start-->
        <a href="#" class="logo "><img class="my_main_logo" src="~/backend/img/backlogo.png" style="max-width: 165px"></a>
        <!--logo end-->

        <div class="top-nav ">
            <ul class="nav pull-right top-menu">
                
                <!-- user login dropdown start-->
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <img alt="" src="~/backend/img/user.png">
                        <span class="username">Super Administrator</span>
                        <b class="caret"></b>
                    </a>


                    <ul class="dropdown-menu extended logout">
                        <div class="log-arrow-up"></div>
                        @Html.Partial("_LoginAdmin")

                    </ul>
                </li>
                <!-- user login dropdown end -->

            </ul>
        </div>
    </header>
    <!--header end-->



    <!--sidebar start-->
    <aside class="">
        <div id="sidebar" class="nav-collapse">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">

                <!--dashboard menu starts-->
                <li>
                    <a href="" class="active">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <!--dashboard menu ends-->
                <!--user menu starts-->
                <li class="sub-menu">
                    <a class="" asp-area="Admin" asp-controller="Users" asp-action="Index">
                        <i class="fa fa-user"></i>
                        <span>Users</span>
                    </a>

                </li>
                <!--user menu ends-->
                <!--Roles and permissions starts-->
                <li class="sub-menu">
                    <a class="" asp-area="Admin" asp-controller="Roles" asp-action="Index">
                        <i class="fa fa-lock"></i>
                        <span>Roles </span>
                    </a>


                </li>
                <!--Roles and permissions ends-->


                <li class="sub-menu">
                    <a class="" asp-area="Admin" asp-controller="News" asp-action="Index">
                        <i class="fa fa-bell"></i>
                        <span>News </span>
                    </a>

                </li>

                <li class="sub-menu">
                    <a class="" asp-area="Admin" asp-controller="Careers" asp-action="Index">
                        <i class="fa fa-star"></i>
                        <span>Careers </span>
                    </a>

                </li>

            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->

    <section id="main-content">

        <section class="wrapper site-min-height">


            @RenderSection("Breadcrumbs", required: false)
            @RenderBody()


        </section>
    </section>




    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/stock.js" asp-append-version="true"></script>
        <script class="include" type="text/javascript" src="~/backend/js/jquery.dcjqaccordion.2.7.js"></script>
        <script src="~/backend/js/jquery.scrollTo.min.js"></script>
        <script src="~/backend/js/jquery.nicescroll.js" type="text/javascript"></script>
        <script src="~/backend/js/slidebars.min.js"></script>
        <script src="~/backend/js/respond.min.js"></script>
        <script src="~/backend/js/bootstrap-validator.min.js" type="text/javascript"></script>
        <script src="~/backend/js/jquery.steps.min.js" type="text/javascript"></script>
        <script src="~/backend/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="~/backend/js/jquery.stepy.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <script src="~/backend/js/common-scripts.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script class="include" type="text/javascript" src="~/backend/js/jquery.dcjqaccordion.2.7.js"></script>
        <script src="~/backend/js/jquery.scrollTo.min.js"></script>
        <script src="~/backend/js/jquery.nicescroll.js" type="text/javascript"></script>
        <script src="~/backend/js/slidebars.min.js"></script>
        <script src="~/backend/js/respond.min.js"></script>
        <script src="~/backend/js/bootstrap-validator.min.js" type="text/javascript"></script>
        <script src="~/backend/js/jquery.steps.min.js" type="text/javascript"></script>
        <script src="~/backend/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="~/backend/js/jquery.stepy.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
        <script src="~/backend/js/common-scripts.js"></script>
    </environment>

    @RenderSection("scripts", required: false)

</body>
</html>

WebApplication/Areas/Admin/Views/Shared/_LeftMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using WebApplication.Identity
@inject UserManager<IdentityUser> UserManager

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/images/system/user-160x160.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@UserManager.GetUserName(User)</p>
                <!-- Status -->
                <i class="fa fa-circle text-success"></i> Online
            </div>
        </div>
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">Navigation</li>
            <!-- Optionally, you can add icons to the links -->
            <li id="menu-dashboard"><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index"><i class="fa fa-dashboard"></i><span>Dashboard</span></a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-tv"></i><span>Home</span></a></li>
            <li id="menu-catalog" class="treeview">
                <!-- catalog tree bar -->
                <a href="#">
                    <i class="fa fa-book"></i> <span>Admin</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a id="menu-admin-user" asp-controller="#" asp-action="List"><i class="fa fa-circle-o"></i><span>User</span></a></li>
                    <li><a id="menu-admin-role" asp-controller="#" asp-action="List"><i class="fa fa-circle-o"></i><span>Role</span></a></li>
                       </ul>
            </li>
            <!-- sales tree bar -->
            <li id="menu-sale" class="treeview">
                <a href="#">
                    <i class="fa fa-shopping-cart"></i> <span>Setting</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a id="menu-sale-orders" asp-controller="#" asp-action="List"><i class="fa fa-circle-o"></i><span>Privacy</span></a></li>
                </ul>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

WebApplication/Areas/Admin/Views/Shared/_LoginAdmin.cshtml
<li><a asp-area="admin" asp-controller="home" asp-action="Index" ><i class=" fa fa-suitcase"></i>Dashboard</a></li>
                            @*<li><a asp-area="Profile" asp-controller="Profile" asp-action="Index" ><i class="fa fa-cog"></i>Profile</a></li>*@
                            <li><a asp-area="" asp-controller="Manage" asp-action="Index"><i class="fa fa-bell-o"></i> Manage</a></li>
                            @*<li><a asp-area="" asp-controller="Help" asp-action="Index"><i class="fa fa-key"></i>Help</a></li>*@
                            <li><a asp-area="" asp-controller="Account" asp-action="LogOff"><i class="fa fa-key"></i>Logout</a></li>